/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/chat/index.vue')['default']
    Drawer: typeof import('./src/components/settings/drawer.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    IGameIconsMagicBroom: typeof import('~icons/game-icons/magic-broom')['default']
    IPhChatCircleTextLight: typeof import('~icons/ph/chat-circle-text-light')['default']
    MarkdownIt: typeof import('./src/components/chat/markdown-it.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/settings/index.vue')['default']
    SettingsInfo: typeof import('./src/components/settings-info/index.vue')['default']
    SliderBar: typeof import('./src/components/slider-bar/index.vue')['default']
  }
}
